name:                lab13-bprog-compiler
version:             0.1.0.0
github:              "tungno/lab13-bprog-compiler"
license:             MIT
author:              "tungno"
maintainer:          "jktungno@gmail.com"
copyright:           "tungno-all-right-reserved"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- transformers
- mtl
- directory
- filepath
- hspec
- QuickCheck
- haskeline

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  lab13-bprog-compiler:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lab13-bprog-compiler

tests:
  lab13-bprog-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lab13-bprog-compiler