name:                lab12-bprog
version:             0.1.0.0
github:              "tungno/lab12-bprog"
license:             BSD-3-Clause
author:              "tungno"
maintainer:          "jktungno@gmail.com"
copyright:           "tungno-all-right-reserved"

extra-source-files:
- README.md
- CHANGELOG.md
- examples/*.bprog
- prelude/*.bprog

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tungno/lab12-bprog#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- mtl
- haskeline
- directory
- filepath
- transformers
- hspec

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - BPROG
    - BPROG.Types
    - BPROG.Error
    - BPROG.Parser
    - BPROG.Interpreter
    - BPROG.Eval
    - BPROG.Prelude
    - BPROG.IO
    - BPROG.Operations.Arithmetic
    - BPROG.Operations.Stack
    - BPROG.Operations.Logic
    - BPROG.Operations.Comparison
    - BPROG.Operations.List
    - BPROG.Operations.Control

executables:
  bprog:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lab12-bprog

tests:
  lab12-bprog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lab12-bprog
    - hspec