name:                haskellLab05
version:             0.1.0.0
github:              "tungno/haskellLab05"
license:             BSD-3-Clause
author:              "tungno"
maintainer:          "jktungno@gmail.com"
copyright:           "tungno-all-right-reserved"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tungno/haskellLab05#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskellLab05-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellLab05

  task1-exe:
    main:                Main.hs
    source-dirs:         app/task1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellLab05

  task2-exe:
    main:               Main.hs
    source-dirs:        app/task2
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskellLab05


  task3-exe:
    main:               Main.hs
    source-dirs:        app/task3
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskellLab05
  
  task4-exe:
    main:               Main.hs
    source-dirs:        app/task4
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskellLab05
  
  bonus-exe:
    main:               Main.hs
    source-dirs:        app/bonus
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskellLab05


tests:
  haskellLab05-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellLab05
    - doctest
