name:                helloworld
version:             0.1.0.0
github:              "tungno/helloworld"
license:             BSD-3-Clause
author:              "tungno"
maintainer:          "jktungno@gmail.com"
copyright:           "tungno-all-right-reserved"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/tungno/helloworld#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  task1-exe:
    main:                Main.hs
    source-dirs:         app/task1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - helloworld

  task2-exe: 
    main:               Main.hs
    source-dirs:        app/task2
    ghc.options: 
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: 
    - helloworld

  task3-exe:
    main:             Main.hs
    source-dirs:      app/task3
    ghc.options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - helloworld

  task4-exe:
    main:                Main.hs
    source-dirs:         app/task4
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - helloworld

tests:
  helloworld-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - helloworld
